### ISSUE TITLE
Allow configuration of file matching rules 

### ISSUE THREAD

**Issue by italomaia** [johnmuhl/nginx-tmbundle#4]
It would be nice to be able to add nginx highlight to files other than nginx.conf 
In my project I have nginx.conf, nginx.conf.dev 
Only nginx.conf has highlight.

**Comment by johnmuhl** [comment]
I no longer use TextMate so don't have any interest in adding features myself. If you want to open PRs for the changes you want I will merge them or give you access to the repo.
