### ISSUE TITLE
How can I add to files.associations?

### ISSUE THREAD

**Issue by H1nk** [johnmuhl/nginx-tmbundle#5]
Is there a way I can add this syntax highlighter to other file extensions in my files.associations?

**Comment by johnmuhl** [comment]
I'm sorry but I haven't used TextMate in years and do not recall how file associations work there. If you figure it out and need any changes made on this side you are welcome to push access.

**Comment by H1nk** [comment]
I just realized I was using a port of this language support bundle. Sorry, I was actually looking to get support for Visual Studio code.
